excavator_pid_controller_node:
  ros__parameters:
    control_frequency: 50.0

    # --- ROS Topics ---
    # Goal topic expects a std_msgs/Float64MultiArray with [boom, arm, bucket] angles in radians
    goal_topic: "/goal_pose"
    # State topic from the simulator
    joint_states_topic: "/dynamic_joint_states" 
    # Command topic for the Gazebo forward position controller
    command_topic: "/manipulator_controller/commands" 

    # --- Joint Configuration ---
    # These MUST match the names in the /dynamic_joint_states message
    joint_names:
      - 'swing_to_boom'
      - 'boom_to_arm'
      - 'arm_to_bucket'

    # --- PID Gains (TUNE THESE!) ---
    # Boom Gains
    boom:
      kp: 5.0  # Proportional: Reacts to current error
      ki: 0.2  # Integral: Eliminates steady-state error
      kd: 1.0  # Derivative: Dampens oscillations
    
    # Arm Gains
    arm:
      kp: 6.0
      ki: 0.25
      kd: 1.2

    # Bucket Gains
    bucket:
      kp: 3.0
      ki: 0.1
      kd: 0.5